import {
  Container,
  Text,
  FormControl,
  FormLabel,
  Heading,
  Input,
  VStack,
  Button,
} from "@chakra-ui/react";
import Head from "next/head";
import {
  fields,
  getDefaultValue,
  getLabel,
  getPrediction,
} from "../logic/wine-quality.api";
import { useState } from "react";

export default function Home() {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<number | null>(null);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        as="form"
        my={10}
        onSubmit={async (e) => {
          e.preventDefault();
          const formData = new FormData(e.target as HTMLFormElement);
          try {
            setLoading(true);
            const res = await getPrediction(formData);
            setResult(res);
          } catch (error) {
            console.error(error);
          } finally {
            setLoading(false);
          }
          console.log(Object.fromEntries(formData));
        }}
      >
        <VStack align={"flex-start"} spacing={2}>
          <VStack align={"flex-start"} spacing={4}>
            <Heading>Qualidade do Vinho</Heading>
            <Text>
              Preencha as informações abaixo para ter uma previsão da qualidade
              esperada do seu vinho.
            </Text>
          </VStack>
          {Object.keys(fields).map((field) => (
            <FormControl key={field}>
              <FormLabel>{getLabel(field as keyof typeof fields)}</FormLabel>
              <Input
                defaultValue={getDefaultValue(field as keyof typeof fields)}
                name={field}
                type="text"
              />
            </FormControl>
          ))}
          <Button isLoading={loading} type="submit">
            Prever qualidade do vinho
          </Button>

          {result && (
            <Text>
              A qualidade do vinho é estimada em <strong>{result}</strong>.
            </Text>
          )}
        </VStack>
      </Container>
    </>
  );
}
